version: '3'
services:
  transmission:
    build: .
    image: rpi-transmission
    volumes:
     - "/media/external:/downloads"
     - "/home/transmission-watch:/home/transmission-watch"
  samba:
    build: .
    image: rpi-samba
    volumes:
     - "/media/external:/data/share"
  kodi:
    build: .
    image: kodi-rpi
    devices:
     - "/dev/tty0:/dev/tty0"
     - "/dev/tty2:/dev/tty2"
     - "/dev/fb0:/dev/fb0"
     - "/dev/input:/dev/input"
     - "/dev/snd:/dev/snd"
     - "/dev/vchiq:/dev/vchiq"
    volumes:
     - "/var/run/dbus:/var/run/dbus"
     - "/etc/localtime:/etc/localtime:ro"
     - "/etc/timezone:/etc/timezone:ro"
     - "/home/pi/kodi-rpi/config:/config/kodi"
     - "/home/pi/kodi-rpi/data:/data"
