version: '3'

services:
  transmission:
    build:
      context: .
      dockerfile: transmission.Dockerfile
    image: rpi-transmission
    restart: unless-stopped
    ports:
     - "127.0.0.1:9091:9091"
     - "51413:51413"
     - "51413:51413/udp"
    volumes:
     - "/home/pi/transmission_docker/transmission:/etc/transmission"
     - "/home/pi/transmission_docker/var_lib_transmission-daemon:/var/lib/transmission-daemon"
     #Map everything from transmission-daemon folder except settings.json because it erases the original when mounted for the first time
     - "/home/pi/transmission_docker/transmission-daemon/blocklists:/etc/transmission-daemon/blocklists"
     - "/home/pi/transmission_docker/transmission-daemon/torrents:/etc/transmission-daemon/torrents"
     - "/home/pi/transmission_docker/transmission-daemon/resume:/etc/transmission-daemon/resume"
     - "/home/pi/transmission_docker/transmission-watch:/home/transmission-watch"
     - "/media/external:/home/downloads"

  samba:
    build:
      context: .
      dockerfile: samba.Dockerfile
    image: rpi-samba
    restart: unless-stopped
    stdin_open: true
    volumes:
     - "/media/external:/data/share:ro"
    ports:
     - "445:445"
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
  couchpotato:
    build:
      context: .
      dockerfile: couchpotato.Dockerfile
    image: couchpotato
    restart: unless-stopped
    stdin_open: true
    volumes:
     - "/home/pi/transmission_docker/transmission-watch:/movies"
     - "/home/pi/couchpotato_config/config:/config"
    ports:
     - "127.0.0.1:5050:5050"
#  kodi:
#    build:
#      context: .
#      dockerfile: kodi.Dockerfile
#    image: kodi-rpi
#    restart: unless-stopped
#    ports:
#     - "127.0.0.1:8080:8080"
#     - "127.0.0.1:9777:9777/udp"
#    devices:
#     - "/dev/tty0:/dev/tty0"
#     - "/dev/tty2:/dev/tty2"
#     - "/dev/fb0:/dev/fb0"
#     - "/dev/input:/dev/input"
#     - "/dev/snd:/dev/snd"
#     - "/dev/vchiq:/dev/vchiq"
#    volumes:
#     - "/media/external:/home/pi/movies"
#     - "/var/run/dbus:/var/run/dbus"
#     - "/etc/localtime:/etc/localtime:ro"
#     - "/etc/timezone:/etc/timezone:ro"
#     - "/home/pi/kodi/config:/config/kodi"
#     - "/home/pi/kodi/data:/data"
#     - "/home/pi/.kodi:/home/pi/.kodi"
