version: '3'

services:
  transmission:
    build: ./rpi-transmission
    image: rpi-transmission
    ports:
     - "9091:9091"
     - "51413:51413"
     - "51413:51413/udp"
    volumes:
     - "/home/pi/transmission_docker/transmission:/etc/transmission"
     - "/home/pi/transmission_docker/var_lib_transmission-daemon:/var/lib/transmission-daemon"
     - "/home/pi/transmission_docker/transmission-daemon:/home/transmission-daemon"
     - "/home/pi/transmission_docker/transmission-watch:/home/transmission-watch"
     - "/media/external:/home/downloads"

  samba:
    build: ./rpi-samba
    image: rpi-samba
    stdin_open: true
    volumes:
     - "/media/external:/data/share:ro"
  kodi:
    build: ./kodi-rpi
    image: kodi-rpi
    ports:
     - "127.0.0.1:8080:8080"
     - "127.0.0.1:9777:9777/udp"
    devices:
     - "/dev/tty0:/dev/tty0"
     - "/dev/tty2:/dev/tty2"
     - "/dev/fb0:/dev/fb0"
     - "/dev/input:/dev/input"
     - "/dev/snd:/dev/snd"
     - "/dev/vchiq:/dev/vchiq"
    volumes:
     - "/var/run/dbus:/var/run/dbus"
     - "/etc/localtime:/etc/localtime:ro"
     - "/etc/timezone:/etc/timezone:ro"
     - "/home/pi/kodi/config:/config/kodi"
     - "/home/pi/kodi/data:/data"
     - "/home/pi/.kodi:/home/pi/.kodi"
